id: P001792
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS20570
  title: ལིའུ་ཧྲའོ་ཆི་ཡི་གཏམ་རྒྱུད།
  author: ''
  volumes:
    c0a01a71f3ab4c2d9ec98f874abd94d1:
      image_group_id: I8LS20572
      title: ''
      volume_number: 1
      total_pages: 393
      base_file: v001.txt
