id: ICAD20ADC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T20:57:44+00:00'
last_modified: '2022-06-07T15:10:44.031075+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20570
  title: ལིའུ་ཧྲའོ་ཆི་ཡི་གཏམ་རྒྱུད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    31CE:
      image_group_id: I8LS20572
      title: ''
      total_pages: 393
      order: 1
      base_file: 31CE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
